vich_uploader:
    db_driver: orm

    mappings:
        artwork_image:
            uri_prefix: /images/artwork
            upload_destination: '%kernel.project_dir%/public/images/artwork'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
